### ISSUE TITLE
KeyError when running --about before configuring

### ISSUE THREAD

**Issue by pnadolny13** [Widen/tap-rest-api-msdk#20]
I noticed that when I run `meltano invoke tap-rest-api-msdk --about` I get:

```bash
File ".../tap_rest_api_msdk/tap.py", line 184, in discover_streams
    for stream in self.config["streams"]:
KeyError: 'streams'
```

I'm not totally sure how the about command works but it seems like its trying to do a discovery but since I havent configured anything yet it fails. Maybe theres should be a safe path that allows the streams to be empty.

**Comment by jlloyd-widen** [comment]
Good catch. I'll see what I can do to resolve it.

**Comment by s7clarke10** [comment]
This issue is resolved.
