### ISSUE TITLE
Considering using the latest pagination classes from SDK

### ISSUE THREAD

**Issue by aaronsteers** [Widen/tap-rest-api-msdk#26]
I'd be curious if the newly launched pagination classes would be helpful for this generic `tap-rest-api` implementation:

- https://github.com/meltano/sdk/pull/732
- New classes documented here: https://sdk.meltano.com/en/latest/reference.html?highlight=pagination#pagination

Feedback on those new SDK classes would be much appreciated, either way.

Thanks!

**Comment by s7clarke10** [comment]
This has been done now @aaronsteers.  PR: https://github.com/Widen/tap-rest-api-msdk/pull/36. 

Hope you are keeping well.
