### ISSUE TITLE
Error when using 'simple_offset_paginator' request style

### ISSUE THREAD

**Issue by dannydeut** [Widen/tap-rest-api-msdk#51]
I tried using this extractor with `pagination_request_style: simple_offset_paginator`. However when I test the config or run the extractor I get the error below.

``` TypeError: __init__() missing 1 required positional argument: 'page_size' ```

I couldn't figure out what I was doing wrong, but after some digging in the code I found out that the plugin contains a bug(?). I forked the repo, applied the 'fix' and the extractor is working me now. I am new to Meltano and not really a python developer, so leave up to the maintainers of this extractor what to do with this. The fix can be found below.

https://github.com/dannydeut/tap-rest-api-msdk/commit/60ef665b375f58b72a6162a50ef99a3ca4828964

BTW great work on this extractor, works very nice.

**Comment by jlloyd-widen** [comment]
@dannydeut Thanks for contributing! Would you mind submitting a PR with this issue (#51) in the description?
